In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### train test split

In [37]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-0.65173596, -0.14111419, -0.58208279, ...,  0.58741498,
         2.96235511,  2.99795358],
       [-0.54717364, -1.20404399, -0.54728983, ..., -0.36695644,
        -0.3471836 ,  0.21748457],
       [-1.44245316, -0.0950001 , -1.3131442 , ..., -0.01812765,
         0.38015264,  1.14109687],
       ...,
       [ 3.12946351,  1.29072835,  3.24800773, ...,  2.58223247,
        -0.85854227,  1.11969218],
       [-0.34935304, -0.68756617, -0.39379149, ..., -0.50361881,
         0.20387683, -0.78586019],
       [-0.15153244,  1.30686828, -0.16784194, ...,  0.04076553,
        -0.38847343, -0.54612768]])

In [9]:
y_train

31     M
386    B
318    B
493    B
428    B
      ..
565    M
379    M
82     M
195    B
100    M
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,

### Numpy arrays to PyTorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [16]:
class NN1():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss





### Important Parameters

In [15]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [17]:
# create model
model = NN1(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.4814534610007595
Epoch: 2, Loss: 3.3550009932828244
Epoch: 3, Loss: 3.2257057244325877
Epoch: 4, Loss: 3.0938002096395794
Epoch: 5, Loss: 2.9568809665876516
Epoch: 6, Loss: 2.813663664855916
Epoch: 7, Loss: 2.6642897581374716
Epoch: 8, Loss: 2.5091712690935863
Epoch: 9, Loss: 2.3497314147569637
Epoch: 10, Loss: 2.1901379773210894
Epoch: 11, Loss: 2.0311681604365037
Epoch: 12, Loss: 1.87714015080205
Epoch: 13, Loss: 1.7284938628019082
Epoch: 14, Loss: 1.5842921242524575
Epoch: 15, Loss: 1.4469577808683485
Epoch: 16, Loss: 1.3183021930699412
Epoch: 17, Loss: 1.205710213995777
Epoch: 18, Loss: 1.1101788407105384
Epoch: 19, Loss: 1.0318333195624454
Epoch: 20, Loss: 0.969738385881967
Epoch: 21, Loss: 0.9220231815882719
Epoch: 22, Loss: 0.8862216058681469
Epoch: 23, Loss: 0.8596670950530357
Epoch: 24, Loss: 0.8398650543514923
Epoch: 25, Loss: 0.8247497221250862


In [18]:
model.weights

tensor([[ 0.1195],
        [ 0.5344],
        [-0.0608],
        [-0.1473],
        [ 0.1914],
        [-0.1041],
        [-0.4984],
        [ 0.3135],
        [ 0.4824],
        [-0.1366],
        [ 0.0253],
        [ 0.3292],
        [ 0.0556],
        [ 0.0057],
        [ 0.1883],
        [ 0.1956],
        [-0.2998],
        [-0.3512],
        [ 0.6623],
        [ 0.0472],
        [ 0.3628],
        [-0.2026],
        [ 0.2686],
        [-0.2149],
        [-0.2585],
        [-0.4321],
        [ 0.2793],
        [-0.0243],
        [-0.0666],
        [ 0.1849]], dtype=torch.float64, requires_grad=True)

In [19]:
model.bias

tensor([-0.1302], dtype=torch.float64, requires_grad=True)

### Evaluation

In [20]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.6177285313606262


**Simple example of the use of NN module :**

In [21]:
import torch
import torch.nn as nn
import torch.optim as optim

In [22]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [23]:
# create dataset
features = torch.rand(15,7)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.6231],
        [0.5906],
        [0.5866],
        [0.5957],
        [0.5898],
        [0.5905],
        [0.6024],
        [0.6132],
        [0.6259],
        [0.6276],
        [0.6014],
        [0.5904],
        [0.5872],
        [0.6113],
        [0.5876]], grad_fn=<SigmoidBackward0>)

In [26]:
!pip install torchinfo

In [27]:
from torchinfo import summary

In [29]:
summary(model, input_size=(15,7))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [15, 1]                   --
├─Sequential: 1-1                        [15, 1]                   --
│    └─Linear: 2-1                       [15, 3]                   24
│    └─ReLU: 2-2                         [15, 3]                   --
│    └─Linear: 2-3                       [15, 1]                   4
│    └─Sigmoid: 2-4                      [15, 1]                   --
Total params: 28
Trainable params: 28
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

**Now using NN module in the uploaded dataset ..**

In [30]:
class NN2(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [31]:
# defining loss function:
loss_function = nn.BCELoss()

**Training pipeline:**

In [40]:
# creating model
model_NN2 = NN2(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model_NN2.parameters(), lr=learning_rate)


X_train_tensor = X_train_tensor.to(torch.float32)
model_NN2 = model_NN2.float()

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model_NN2(X_train_tensor)

  # loss calculate
  y_train_tensor = y_train_tensor.float()

  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 1.0154237747192383
Epoch: 2, Loss: 0.6924535632133484
Epoch: 3, Loss: 0.5301522016525269
Epoch: 4, Loss: 0.44357094168663025
Epoch: 5, Loss: 0.3899240791797638
Epoch: 6, Loss: 0.3530542850494385
Epoch: 7, Loss: 0.32587480545043945
Epoch: 8, Loss: 0.3048178255558014
Epoch: 9, Loss: 0.28789398074150085
Epoch: 10, Loss: 0.2739056348800659
Epoch: 11, Loss: 0.2620869278907776
Epoch: 12, Loss: 0.2519243359565735
Epoch: 13, Loss: 0.24305976927280426
Epoch: 14, Loss: 0.23523522913455963
Epoch: 15, Loss: 0.22825965285301208
Epoch: 16, Loss: 0.22198815643787384
Epoch: 17, Loss: 0.21630869805812836
Epoch: 18, Loss: 0.2111329287290573
Epoch: 19, Loss: 0.2063901275396347
Epoch: 20, Loss: 0.202022984623909
Epoch: 21, Loss: 0.19798433780670166
Epoch: 22, Loss: 0.19423504173755646
Epoch: 23, Loss: 0.19074222445487976
Epoch: 24, Loss: 0.18747805058956146
Epoch: 25, Loss: 0.18441878259181976
